package com.stonesoupprogramming.marathonscrape.enums

enum class Gender(val code : String){
    MALE("M"),
    FEMALE("W"),
    UNASSIGNED("U")
}

enum class MarathonSources(val arg : String, val endYear: Int = 2017, val startYear : Int = 2014){
    Canberra("--canberra"),
    //NOTE: Add commandline args above this line
    Chester("--chester"),
    Snowdonia("--snowdonia"),
    California("--california"),
    RocketCity("--rocket-city"),
    Dallas("--dallas"),
    Charleston("--charleston"),
    Carlsbad("--carlsbad"),
    NewOrleans("--new-orleans"),
    Woodlands("--woodlands"),
    Phoenix("--phoenix"),
    NapaValley("--napa-valley"),
    Illinois("--illinois"),
    OklahomaCity("--oklahoma-city"),
    GlassCity("--glass-city"),
    Rotorua("--rotorua"),
    Pittsburgh("--pittsburg"),
    OC("--oc"),
    Seattle("--seattle"),
    Miami("--miami"),
    Portland("--portland"),
    Lincoln("--lincoln"),
    CoxSports("--cox-sports"),
    MiltonKeynes("--milton-keynes"),
    Burlington("--burlington"),
    MountainsToBeach("--mountains-to-beach"),
    ChiangMai("--chaing-mai"),
    CorkCity("--cork-city"),
    UtahValley("--utah-valley"),
    Missoula("--missoula"),
    Erie("--erie-marathon"),
    Seamtown("--seamtown"),
    Mohawk("--mohawk"),
    StLouis("--st-louis"),
    RockRollLasVegas("--rock-n-roll-las-vegas"),
    LongBeach("--long-beach"),
    PoweradeMonterrery("--powerade-monterrey"),
    Milwaukee("--milwaukee"),
    Istanbul("--istanbul"),
    Philadelphia("--philadelphia"),
    Belfast("--belfast"),
    Berlin("--berlin"),
    MyrtleBeach("--myrtle-beach"),
    Maritzburg("--maritzburg"),
    Cottonwood("--cottonwood"),
    Helsinki("--helsinki"),
    NoredaRiga("--noreda-riga"),
    PfChangsArizona("--pf-changs-arizona"),
    Unassigned("")
}